apiVersion: v1
kind: Service
metadata:
  name: {{ include "sp-ruleengine.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sp-ruleengine.name" . }}
    helm.sh/chart: {{ include "sp-ruleengine.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: rulesengine.k8s-test.stockpiletest.com
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sp-ruleengine.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
