- hosts: localhost
  vars:
    ImageName: ""
    Namespace: ""
    imageTag: ""
    Name: ""
    ChartName: ""
  gather_facts: no
  connection: local
  tasks:
    - name: Create Namespace {{ Namespace }}
      command: "kubectl create namespace {{ Namespace }}"
      ignore_errors: yes
    - name: Deploy sp-registry
      command: "helm install --name={{ Name }} --namespace={{ Namespace }} {{ ChartName }}  --set image.repository={{ ImageName }} --set image.tag={{ imageTag }} --set namespace={{ Namespace }}"
      delegate_to: localhost
      ignore_errors: yes
    - name: Update sp-registry
      command: "helm upgrade --namespace={{ Namespace }} --set image.repository={{ ImageName }} --set image.tag={{ imageTag }} --set namespace={{ Namespace }} {{ Name }} {{ ChartName }}"
      delegate_to: localhost
      ignore_errors: yes

